
A:
	g++ -std=c++17 A.cpp -o A && ./A < input.txt > output.txt

B:
	g++ -std=c++17 B.cpp -o B && ./B < input.txt > output.txt

C:
	g++ -std=c++17 C.cpp -o C && ./C < input.txt > output.txt

clean:
	rm ./A && rm ./B && rm ./C